runtime: python38
instance_class: F1

# ドキュメントルートアクセス時の spin up を回避するため
# あえて static html を返す
handlers:
- url: /
  static_files: static/gae_index.html
  upload: static/gae_index.html
 
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
