name: deploy

on:
  workflow_dispatch:
    inputs:
      deployType:
        description: "Deploy type [stg/prod]"
        required: true
        default: 'stg'
 
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: "checkout"
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: "prepare before deploy"
      run: make pre-deploy

    - name: "deploy to staging environment"
      if: ${{ github.events.inputs.deployType == 'stg' }}
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GCLOUD_AUTH }}
        version: stg
        promote: false

    - name: "deploy to production environment"
      if: ${{ github.events.inputs.deployType == 'prod' }}
      uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
      with:
        credentials: ${{ secrets.GCLOUD_AUTH }}
